#+TITLE: ktkbot
#+DESCRIPTION: Readme for ktkbot.
#+AUTHOR: Mathias Estrup

ktkbot is a bot that sends push notifications when new tennis events are put up for Kløvermarkens Tennis Klub (KTK).

KTK has no automatic notification system for when new events (i.e. training lessons) are made available on the booking website. Joining events requires doing so before the number of available spots fill up. By getting these notifications, you gain the advantage of knowing immediately when events become available.

* Installation
Either download the latest binary release or clone the repository.

** Download Binary (easy)
Download the [[https://github.com/mestru17/ktkbot/releases/latest][latest release]] and place it wherever you want.

** Clone the repository (requires [[https://doc.rust-lang.org/cargo/getting-started/installation.html][Cargo]])
Clone the repository and build from source yourself to get the newest version including unreleased changes:
#+begin_src bash
$ git clone https://github.com/mestru17/ktkbot.git
$ cd ktkbot
$ cargo build --release
#+end_src

This compiles ktkbot and puts the executable in the =target/release= directory.

* Usage
Either add the =ktkbot= executable to your =PATH= or simply run it from whichever directory it resides in. Note that you need to supply your Pushover API and group keys as arguments at the moment.

** Run from anywhere (i.e. ktkbot is in =PATH=)
#+begin_src bash
$ ktkbot [OPTIONS] <PUSHOVER API KEY> <PUSHOVER GROUP KEY>
#+end_src

** Run from directory
#+begin_src bash
$ ./path/to/ktkbot [OPTIONS] <PUSHOVER API KEY> <PUSHOVER GROUP KEY>
#+end_src

** Options
By passing the ~--help~ flag, you can also get a more in-depth usage description that includes configuration options:
#+begin_src bash
$ ktkbot --help
ktkbot 0.12.0
Mathias Estrup
Sends KTK event push notifications.

USAGE:
    ktkbot [OPTIONS] <PUSHOVER API KEY> <PUSHOVER GROUP KEY>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -e, --events-file <FILE>           Sets the file to save events to. [default: events.json]
    -f, --fetch-interval <SECONDS>     Sets the delay in between fetching events. [default: 120]
    -d, --log-directory <DIRECTORY>    Sets the directory to put log files in. [default: logs]
    -l, --log-level <LOG LEVEL>        Sets the level of logging. [default: info]  [possible values: error, warn, info,
                                       debug, trace]

ARGS:
    <PUSHOVER API KEY>      The API key to use for sending Pushover notifications.
    <PUSHOVER GROUP KEY>    The group key to use for sending Pushover notifications.
#+end_src
